version: '3.1'

services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_DB: odoo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: malgytYMprctnPKfvpAkafaIEyqkBMSt
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo:
    build: .
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo_db
      - ADMIN_USER=postgres
      - ADMIN_PASSWORD=malgytYMprctnPKfvpAkafaIEyqkBMSt
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo

volumes:
  odoo-web-data:
    name: odoo-18-docker_odoo-web-data
  odoo-db-data:
    name: odoo-18-docker_odoo-db-data
