version: '3.9'

services:
  odoo:
    image: odoo:18
    container_name: odoo_local
    ports:
      - "8069:8069"
    environment:
      - PGHOST=postgresql://postgres:aabkcRKIyFheDRyEWnMcRbgKSnJyOmlw@turntable.proxy.rlwy.net:23730/railway
      - PGUSER=postgres
      - PGPASSWORD=aabkcRKIyFheDRyEWnMcRbgKSnJyOmlw
      - PGDATABASE=railway
      - PGPORT=5432
    command: odoo -d railway --db_sslmode=prefer
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo

volumes:
  odoo_data:
