# Railway Configuration File
# Este archivo le dice a Railway cómo construir y ejecutar tu aplicación

[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/web/health"
healthcheckTimeout = 300

[env]
# Variables específicas para addons personalizados
ODOO_ADDONS_PATH = "/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons"
ODOO_DATA_DIR = "/var/lib/odoo"
ODOO_LOG_LEVEL = "info"

# Variable opcional para instalar dependencias adicionales
# INSTALL_OPTIONAL_DEPS = "true"
